version: "3"
services:
  fastapi:
    build: .
    container_name: api_server
    volumes:
      - ./app:/app
    ports:
      - 80:80
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  database:
    image: postgres:12-alpine
    container_name: db_server
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
